---    
- hosts: switches
  user: root
  roles:
    - common
    - switches
 
- hosts: servers
  user: root
  roles:
    - common
    - servers

- hosts: external
  user: root
  roles:
    - common
    - external

